local M = {}

local function hl(group, spec)
  vim.api.nvim_set_hl(0, group, spec)
end

function M.load(variant)
  variant = variant or (vim.o.background == "light" and "light" or "dark")
  vim.o.background = variant

  if vim.g.colors_name then vim.cmd("hi clear") end
  if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end

  vim.g.colors_name = "claudecolor"
  vim.o.termguicolors = true

  local p = require("claudecolor.palette")[variant]

  -- Editor UI
  hl("Normal",       { fg = p.fg, bg = p.bg })
  hl("NormalNC",     { fg = p.fg, bg = p.bg })
  hl("NormalFloat",  { fg = p.fg, bg = p.bg_float })
  hl("FloatBorder",  { fg = p.fg_subtle, bg = p.bg_float })
  hl("FloatTitle",   { fg = p.accent, bg = p.bg_float, bold = true })

  hl("Cursor",       { fg = p.bg, bg = p.fg })
  hl("CursorLine",   { bg = p.bg_alt })
  hl("CursorColumn", { bg = p.bg_alt })
  hl("ColorColumn",  { bg = p.bg_alt })
  hl("LineNr",       { fg = p.fg_subtle })
  hl("CursorLineNr", { fg = p.accent, bold = true })
  hl("SignColumn",   { bg = p.bg })
  hl("FoldColumn",   { fg = p.fg_subtle, bg = p.bg })
  hl("Folded",       { fg = p.fg_dim, bg = p.bg_alt })

  hl("Visual",       { bg = p.bg_sel })
  hl("VisualNOS",    { bg = p.bg_sel })
  hl("Search",       { fg = p.bg, bg = p.yellow })
  hl("IncSearch",    { fg = p.bg, bg = p.accent })
  hl("CurSearch",    { fg = p.bg, bg = p.accent })
  hl("MatchParen",   { fg = p.accent, bold = true, underline = true })

  hl("StatusLine",     { fg = p.fg, bg = p.bg_alt })
  hl("StatusLineNC",   { fg = p.fg_dim, bg = p.bg_alt })
  hl("WinSeparator",   { fg = p.fg_faint })
  hl("VertSplit",      { fg = p.fg_faint })
  hl("TabLine",        { fg = p.fg_dim, bg = p.bg_alt })
  hl("TabLineFill",    { bg = p.bg_alt })
  hl("TabLineSel",     { fg = p.accent, bg = p.bg, bold = true })
  hl("WinBar",         { fg = p.fg_dim, bg = p.bg })
  hl("WinBarNC",       { fg = p.fg_subtle, bg = p.bg })

  hl("Pmenu",          { fg = p.fg, bg = p.bg_float })
  hl("PmenuSel",       { fg = p.bg, bg = p.accent, bold = true })
  hl("PmenuSbar",      { bg = p.bg_alt })
  hl("PmenuThumb",     { bg = p.fg_subtle })
  hl("PmenuKind",      { fg = p.blue, bg = p.bg_float })
  hl("PmenuKindSel",   { fg = p.bg, bg = p.accent })
  hl("PmenuExtra",     { fg = p.fg_dim, bg = p.bg_float })
  hl("PmenuExtraSel",  { fg = p.bg, bg = p.accent })

  hl("NonText",        { fg = p.fg_faint })
  hl("Whitespace",     { fg = p.fg_faint })
  hl("SpecialKey",     { fg = p.fg_subtle })
  hl("EndOfBuffer",    { fg = p.bg })
  hl("Conceal",        { fg = p.fg_dim })

  hl("MsgArea",        { fg = p.fg, bg = p.bg })
  hl("ModeMsg",        { fg = p.accent, bold = true })
  hl("MoreMsg",        { fg = p.accent })
  hl("Question",       { fg = p.accent })
  hl("WarningMsg",     { fg = p.yellow })
  hl("ErrorMsg",       { fg = p.red })
  hl("Directory",      { fg = p.accent })
  hl("Title",          { fg = p.accent, bold = true })

  -- Vim syntax
  hl("Comment",      { fg = p.fg_dim, italic = true })
  hl("Constant",     { fg = p.yellow })
  hl("String",       { fg = p.green })
  hl("Character",    { fg = p.green })
  hl("Number",       { fg = p.yellow })
  hl("Float",        { fg = p.yellow })
  hl("Boolean",      { fg = p.yellow })
  hl("Identifier",   { fg = p.fg })
  hl("Function",     { fg = p.blue })
  hl("Statement",    { fg = p.purple })
  hl("Conditional",  { fg = p.purple })
  hl("Repeat",       { fg = p.purple })
  hl("Label",        { fg = p.purple })
  hl("Operator",     { fg = p.fg })
  hl("Keyword",      { fg = p.purple })
  hl("Exception",    { fg = p.red })
  hl("PreProc",      { fg = p.accent })
  hl("Include",      { fg = p.accent })
  hl("Define",       { fg = p.accent })
  hl("Macro",        { fg = p.accent })
  hl("Type",         { fg = p.cyan })
  hl("StorageClass", { fg = p.cyan })
  hl("Structure",    { fg = p.cyan })
  hl("Typedef",      { fg = p.cyan })
  hl("Special",      { fg = p.accent })
  hl("SpecialChar",  { fg = p.accent })
  hl("Tag",          { fg = p.blue })
  hl("Delimiter",    { fg = p.fg_dim })
  hl("SpecialComment", { fg = p.fg_dim, italic = true })
  hl("Debug",        { fg = p.red })
  hl("Underlined",   { fg = p.blue, underline = true })
  hl("Error",        { fg = p.red })
  hl("Todo",         { fg = p.accent, bg = p.bg_alt, bold = true })

  -- Treesitter
  hl("@variable",              { fg = p.fg })
  hl("@variable.builtin",      { fg = p.accent })
  hl("@variable.parameter",    { fg = p.fg, italic = true })
  hl("@variable.member",       { fg = p.fg })
  hl("@constant",              { fg = p.yellow })
  hl("@constant.builtin",      { fg = p.yellow })
  hl("@constant.macro",        { fg = p.accent })
  hl("@module",                { fg = p.cyan })
  hl("@label",                 { fg = p.purple })
  hl("@string",                { fg = p.green })
  hl("@string.escape",         { fg = p.accent })
  hl("@string.special",        { fg = p.accent })
  hl("@character",             { fg = p.green })
  hl("@number",                { fg = p.yellow })
  hl("@boolean",               { fg = p.yellow })
  hl("@float",                 { fg = p.yellow })
  hl("@function",              { fg = p.blue })
  hl("@function.builtin",      { fg = p.blue })
  hl("@function.call",         { fg = p.blue })
  hl("@function.macro",        { fg = p.accent })
  hl("@function.method",       { fg = p.blue })
  hl("@constructor",           { fg = p.cyan })
  hl("@operator",              { fg = p.fg })
  hl("@keyword",               { fg = p.purple })
  hl("@keyword.function",      { fg = p.purple })
  hl("@keyword.return",        { fg = p.purple })
  hl("@keyword.operator",      { fg = p.purple })
  hl("@keyword.import",        { fg = p.accent })
  hl("@type",                  { fg = p.cyan })
  hl("@type.builtin",          { fg = p.cyan })
  hl("@type.definition",       { fg = p.cyan })
  hl("@attribute",             { fg = p.accent })
  hl("@property",              { fg = p.fg })
  hl("@comment",               { fg = p.fg_dim, italic = true })
  hl("@comment.todo",          { fg = p.accent, bold = true })
  hl("@comment.note",          { fg = p.blue, bold = true })
  hl("@comment.warning",       { fg = p.yellow, bold = true })
  hl("@comment.error",         { fg = p.red, bold = true })
  hl("@punctuation.delimiter", { fg = p.fg_dim })
  hl("@punctuation.bracket",   { fg = p.fg_dim })
  hl("@punctuation.special",   { fg = p.accent })
  hl("@tag",                   { fg = p.blue })
  hl("@tag.attribute",         { fg = p.accent })
  hl("@tag.delimiter",         { fg = p.fg_dim })

  -- Markdown
  hl("@markup.heading",        { fg = p.accent, bold = true })
  hl("@markup.heading.1",      { fg = p.accent, bold = true })
  hl("@markup.heading.2",      { fg = p.blue, bold = true })
  hl("@markup.heading.3",      { fg = p.cyan, bold = true })
  hl("@markup.heading.4",      { fg = p.purple, bold = true })
  hl("@markup.strong",         { fg = p.fg, bold = true })
  hl("@markup.italic",         { fg = p.fg, italic = true })
  hl("@markup.strikethrough",  { fg = p.fg_dim, strikethrough = true })
  hl("@markup.link",           { fg = p.blue, underline = true })
  hl("@markup.link.url",       { fg = p.blue, underline = true })
  hl("@markup.link.label",     { fg = p.blue, underline = true })
  hl("@markup.raw",            { fg = p.accent, bg = p.bg_alt })
  hl("@markup.raw.block",      { bg = p.bg_alt })
  hl("@markup.quote",          { fg = p.fg_dim, italic = true })
  hl("@markup.list",           { fg = p.accent })

  -- LSP / Diagnostic
  hl("DiagnosticError",            { fg = p.red })
  hl("DiagnosticWarn",             { fg = p.yellow })
  hl("DiagnosticInfo",             { fg = p.blue })
  hl("DiagnosticHint",             { fg = p.cyan })
  hl("DiagnosticOk",               { fg = p.green })
  hl("DiagnosticUnderlineError",   { sp = p.red, undercurl = true })
  hl("DiagnosticUnderlineWarn",    { sp = p.yellow, undercurl = true })
  hl("DiagnosticUnderlineInfo",    { sp = p.blue, undercurl = true })
  hl("DiagnosticUnderlineHint",    { sp = p.cyan, undercurl = true })
  hl("DiagnosticVirtualTextError", { fg = p.red, bg = p.bg_alt })
  hl("DiagnosticVirtualTextWarn",  { fg = p.yellow, bg = p.bg_alt })
  hl("DiagnosticVirtualTextInfo",  { fg = p.blue, bg = p.bg_alt })
  hl("DiagnosticVirtualTextHint",  { fg = p.cyan, bg = p.bg_alt })

  hl("LspReferenceText",   { bg = p.bg_sel })
  hl("LspReferenceRead",   { bg = p.bg_sel })
  hl("LspReferenceWrite",  { bg = p.bg_sel, bold = true })
  hl("LspSignatureActiveParameter", { fg = p.accent, bold = true })
  hl("LspInlayHint",       { fg = p.fg_subtle, bg = p.bg_alt, italic = true })

  -- Diff
  hl("DiffAdd",     { bg = p.diff_add })
  hl("DiffChange",  { bg = p.diff_change })
  hl("DiffDelete",  { bg = p.diff_delete })
  hl("DiffText",    { bg = p.diff_change, bold = true })

  hl("Added",       { fg = p.green })
  hl("Changed",     { fg = p.yellow })
  hl("Removed",     { fg = p.red })

  -- Git signs
  hl("GitSignsAdd",    { fg = p.green })
  hl("GitSignsChange", { fg = p.yellow })
  hl("GitSignsDelete", { fg = p.red })

  -- Spell
  hl("SpellBad",   { sp = p.red, undercurl = true })
  hl("SpellCap",   { sp = p.yellow, undercurl = true })
  hl("SpellLocal", { sp = p.blue, undercurl = true })
  hl("SpellRare",  { sp = p.purple, undercurl = true })

  -- Telescope
  hl("TelescopeNormal",         { fg = p.fg, bg = p.bg_float })
  hl("TelescopeBorder",         { fg = p.fg_subtle, bg = p.bg_float })
  hl("TelescopePromptNormal",   { fg = p.fg, bg = p.bg_alt })
  hl("TelescopePromptBorder",   { fg = p.bg_alt, bg = p.bg_alt })
  hl("TelescopePromptTitle",    { fg = p.bg, bg = p.accent, bold = true })
  hl("TelescopePreviewTitle",   { fg = p.bg, bg = p.blue, bold = true })
  hl("TelescopeResultsTitle",   { fg = p.bg_float, bg = p.bg_float })
  hl("TelescopeSelection",      { fg = p.fg, bg = p.bg_sel, bold = true })
  hl("TelescopeMatching",       { fg = p.accent, bold = true })
  hl("TelescopePromptPrefix",   { fg = p.accent })

  -- WhichKey
  hl("WhichKey",           { fg = p.accent, bold = true })
  hl("WhichKeyGroup",      { fg = p.blue })
  hl("WhichKeyDesc",       { fg = p.fg })
  hl("WhichKeySeparator",  { fg = p.fg_subtle })
  hl("WhichKeyFloat",      { bg = p.bg_float })
  hl("WhichKeyBorder",     { fg = p.fg_subtle, bg = p.bg_float })

  -- Snacks / Notify / Trouble (common group names)
  hl("SnacksNormal",          { fg = p.fg, bg = p.bg_float })
  hl("SnacksBorder",          { fg = p.fg_subtle, bg = p.bg_float })
  hl("SnacksPickerMatch",              { fg = p.accent, bold = true })
  hl("SnacksPickerDir",                { fg = p.accent })
  hl("SnacksPickerDirectory",          { fg = p.accent })
  hl("SnacksPickerTree",               { fg = p.fg_subtle })
  hl("SnacksPickerFile",               { fg = p.fg })
  hl("SnacksPickerIcon",               { fg = p.accent })
  hl("SnacksPickerTotals",             { fg = p.fg_dim })
  hl("SnacksPickerGitStatusUntracked", { fg = p.accent_alt })
  hl("SnacksExplorerDir",              { fg = p.accent })
  hl("SnacksExplorerDirOpen",          { fg = p.accent, bold = true })
  hl("TroubleNormal",      { fg = p.fg, bg = p.bg_alt })
  hl("TroubleText",        { fg = p.fg })
  hl("NotifyERRORBorder",  { fg = p.red })
  hl("NotifyWARNBorder",   { fg = p.yellow })
  hl("NotifyINFOBorder",   { fg = p.blue })
  hl("NotifyHINTBorder",   { fg = p.cyan })

  -- IndentBlankline
  hl("IblIndent",     { fg = p.fg_faint })
  hl("IblScope",      { fg = p.fg_subtle })
  hl("IblWhitespace", { fg = p.fg_faint })

  -- render-markdown.nvim (links & wiki links)
  hl("RenderMarkdownLink",     { fg = p.blue, underline = true })
  hl("RenderMarkdownWikiLink", { fg = p.blue, underline = true })

  -- Obsidian.nvim (future-proof, user has obsidian-link.nvim but may add obsidian.nvim)
  hl("ObsidianRefText",     { fg = p.blue, underline = true })
  hl("ObsidianExtLinkIcon", { fg = p.fg_dim })
  hl("ObsidianTag",         { fg = p.accent })
  hl("ObsidianTodo",        { fg = p.accent, bold = true })
  hl("ObsidianDone",        { fg = p.green })
  hl("ObsidianHighlightText", { fg = p.accent, bg = p.bg_alt })
end

return M
